sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t tomkiworld/robo-joker -f .Dockerfile.dev .

script:
  - docker run -e CI=true tomkiworld/robo-joker npm run test
